import { ArrowLeft, Calendar, Clock, User } from "lucide-react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { EarlyAccessDialog } from "@/components/early-access-dialog"
import { PageShell, Section, Container } from "@/components/layout"
import { TYPOGRAPHY } from "@/lib/layout-constants"
import { cn } from "@/lib/utils"

export default function PricingPhilosophyPage() {
  return (
    <PageShell>
      {/* Hero Section */}
      <Section variant="white" isHero>
        <Container maxWidth="narrow">
          <Link href="/resources" className={cn("inline-flex items-center text-primary-600 hover:text-primary-700 mb-6 md:mb-8", TYPOGRAPHY.subtext)}>
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Resources
          </Link>

          <div className="flex items-center gap-4 text-sm text-gray-500 mb-4">
            <div className="flex items-center gap-1">
              <Calendar className="w-4 h-4" />
              Nov 11, 2025
            </div>
            <div className="flex items-center gap-1">
              <Clock className="w-4 h-4" />6 min read
            </div>
            <div className="flex items-center gap-1">
              <User className="w-4 h-4" />
              Vinod Lakhani
            </div>
          </div>

          <h1 className={cn(TYPOGRAPHY.h1, "text-gray-900 mb-4 md:mb-6")}>
            Why WeLeap's Pricing Is Different (and Built for You)
          </h1>

          <p className={cn(TYPOGRAPHY.body, "text-gray-600 leading-relaxed mb-6 md:mb-8")}>
            Most financial apps make more money when you spend more, borrow more, or sign up for products you don't actually need. WeLeap was built to break that model.
          </p>

          <div className="mb-6 md:mb-8">
            <img
              src="/images/Pricing.png"
              alt="Comparison diagram showing Old Model vs WeLeap Model with aligned incentives"
              className="w-full h-auto object-contain rounded-lg shadow-lg"
            />
          </div>
        </Container>
      </Section>

      {/* Article Content */}
      <Section variant="white">
        <Container maxWidth="narrow">
          <article className="prose prose-lg max-w-none">
            <div className={cn(TYPOGRAPHY.body, "text-gray-700 space-y-4 md:space-y-6")}>
              <p>
                If you've ever wondered why so many financial tools push credit cards, loans, or constant upsells, the answer is simple: their incentives aren't aligned with yours.
              </p>

              <p>
                Most platforms get paid when you open a new card, take out a loan, roll over debt, or click the "top offer" (which often pays the highest referral fee). That doesn't make them evil — but it does mean their advice isn't always neutral.
              </p>

              <p>
                <strong>WeLeap takes a different approach.</strong>
              </p>

              <p>
                <strong>Our Free plan is actually free.</strong> At WeLeap, the Free plan is designed to stay free. You get a clear view of your finances, insights into spending, income, and savings, and guidance without pressure.
              </p>

              <p>
                When Free users choose to sign up for optional financial products through WeLeap, referral or transaction fees may be generated. Those fees help keep the platform running. No hidden subscriptions. No dark patterns.
              </p>

              <p>
                <strong>Plus changes where the money flows.</strong> The real shift happens with Plus. Plus members pay a simple monthly subscription. But here's the key difference: 100% of product-related transaction and referral fees generated by Plus members flow into the WeLeap Community Fund — not to WeLeap.
              </p>

              <p>
                That means you're not funding us with your financial decisions. You're funding each other. The upside goes back to the community, not a corporate balance sheet. WeLeap's incentives stay clean: help you make better decisions, not more transactions.
              </p>

              <p>
                <strong>Referrals that reward participation, not spam.</strong> We didn't want referrals to feel like gimmicks either. So we built a simple system: 3 credits = 1 free month of Plus. Earn 9 credits, and you unlock governance rights in the Community Fund. Earn more, and you unlock deeper participation and long-term perks.
              </p>

              <p>
                Referrals aren't about growth hacks. They're about rewarding people who help grow a healthier financial ecosystem.
              </p>

              <p>
                <strong>Why this matters.</strong> WeLeap isn't trying to win by selling you more financial products. We're trying to win by aligning incentives, being explicit about how money moves, and giving users a real stake in the system. That's why our pricing looks different — because the values behind it are different.
              </p>

              <p>
                <strong>💡 Your takeaway:</strong> Join early. Get Plus free during Early Access. And see what it feels like when your financial choices actually benefit your community — not just a platform.
              </p>
            </div>
          </article>
        </Container>
      </Section>

      {/* CTA Section */}
      <Section variant="white" className="text-center">
        <Container maxWidth="narrow">
          <EarlyAccessDialog signupType="resource">
            <Button className="bg-primary-600 hover:bg-primary-700 text-white px-8 md:px-10 py-3 md:py-4 rounded-xl font-medium shadow-lg transition-all duration-200 hover:shadow-xl">
              Join Waitlist
            </Button>
          </EarlyAccessDialog>
          <p className={cn(TYPOGRAPHY.body, "text-gray-600 mt-4 md:mt-6")}>
            Let's build a future where real finance meets real life.
          </p>
        </Container>
      </Section>

      {/* Footer */}
      <footer className="bg-white border-t border-gray-200 py-8 px-6">
        <Container>
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <div className="flex items-center gap-3">
              <img src="/images/weleap-logo.png" alt="WeLeap" className="h-7 w-auto" />
            </div>
            <div className="flex flex-col md:flex-row items-center gap-2 md:gap-4 text-gray-500 text-sm">
              <p>© 2024 WeLeap.</p>
              <Link href="/privacy-policy" target="_blank" rel="noopener noreferrer" className="hover:underline">
                Privacy Policy
              </Link>
              <Link href="/terms-of-service" className="hover:underline">
                Terms of Service
              </Link>
            </div>
          </div>
        </Container>
      </footer>
    </PageShell>
  )
}
